### ISSUE TITLE
Issue with running locally

### ISSUE THREAD

**Issue by sutyum** [Technoculture/personal-graph#36]
```py
>>> from personal_graph.graph import GraphDB, OllamaClient, OllamaEmbeddingClient
from personal_graph.graph_generator import OpenAITextToGraphParser
from personal_graph.database import SQLite
from personal_graph.vector_store import VliteVSS

phi3 = OllamaClient(model_name="phi3")
nomic_embed = OllamaEmbeddingClient(model_name="nomic-embed-text")

storage_db = SQLite(local_path="./local.db", vector0_so_path="/path/to/vector0/extension", vss0_so_path="/path/to/vss0/extension")
vector_store = VliteVSS(collection="./vectors")

graph_generator=OpenAITextToGraphParser(llm_client=phi3)
print(graph_generator) # Should print the InstructorGraphGenerator

with GraphDB(
    database=storage_db,
    vector_store=vector_store,
    graph_generator=graph_generator
  ) as db:
    print(db)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'OllamaClient' from 'personal_graph.graph' (/Users/satyamtiwary/Documents/Pytorch-Things/personal-graph/personal_graph/graph.py)
>>> from personal_graph.graph_generator import OpenAITextToGraphParser
>>> from personal_graph.database import SQLite
>>> from personal_graph.vector_store import VliteVSS
>>>
>>> phi3 = OllamaClient(model_name="phi3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'OllamaClient' is not defined
>>> nomic_embed = OllamaEmbeddingClient(model_name="nomic-embed-text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'OllamaEmbeddingClient' is not defined
>>>
>>> storage_db = SQLite(local_path="./local.db", vector0_so_path="/path/to/vector0/extension", vss0_so_path="/path/to/vss0/extension")
>>> vector_store = VliteVSS(collection="./vectors")
>>>
>>> graph_generator=OpenAITextToGraphParser(llm_client=phi3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'phi3' is not defined
>>> print(graph_generator) # Should print the InstructorGraphGenerator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'graph_generator' is not defined
>>>
>>> with GraphDB(
...     database=storage_db,
...     vector_store=vector_store,
...     graph_generator=graph_generator
...   ) as db:
...     print(db)
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
NameError: name 'graph_generator' is not defined
```

**Comment by sutyum** [comment]
Also would need to update `storage_db = SQLite(local_path="./local.db", vector0_so_path="/path/to/vector0/extension", vss0_so_path="/path/to/vss0/extension")` to `storage_db = SQLite(local_path="./local.db")` in the README
