### ISSUE TITLE
Issue with trying first example

### ISSUE THREAD

**Issue by sutyum** [Technoculture/personal-graph#37]
```py
(personal-graph-py3.11) ❯ python                                                                                                                                                               personal-graph/git/main
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from personal_graph import GraphDB
>>> from personal_graph.text import text_to_graph
>>> from personal_graph.vector_store import VliteVSS
>>> vector_store = VliteVSS(collection="memories", model_name="mixedbread-ai/mxbai-embed-large-v1")
>>> graph = GraphDB(vector_store=vector_store)
[VLite.__init__] Initializing VLite with device: mps

[VLite.__init__] Execution time: 1.39627 seconds
[VLite.__init__] Using device: mps
>>>
>>> g = text_to_graph("Alice is Bob's sister. Bob works at Google.")

Traceback (most recent call last):
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/satyamtiwary/Documents/Pytorch-Things/personal-graph/personal_graph/text.py", line 11, in text_to_graph
    kg = graph_generator.generate(text)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Documents/Pytorch-Things/personal-graph/personal_graph/graph_generator/generator.py", line 37, in generate
    knowledge_graph = client.chat.completions.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/client.py", line 74, in create
    return self.create_fn(
           ^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/patch.py", line 147, in new_create_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/retry.py", line 143, in retry_sync
    for attempt in max_retries:
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/retry.py", line 146, in retry_sync
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 950, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 960, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Comment by anubhuti24** [comment]
> ```python
> (personal-graph-py3.11) ❯ python                                                                                                                                                               personal-graph/git/main
> Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from personal_graph import GraphDB
> >>> from personal_graph.text import text_to_graph
> >>> from personal_graph.vector_store import VliteVSS
> >>> vector_store = VliteVSS(collection="memories", model_name="mixedbread-ai/mxbai-embed-large-v1")
> >>> graph = GraphDB(vector_store=vector_store)
> [VLite.__init__] Initializing VLite with device: mps
> 
> [VLite.__init__] Execution time: 1.39627 seconds
> [VLite.__init__] Using device: mps
> >>>
> >>> g = text_to_graph("Alice is Bob's sister. Bob works at Google.")
> 
> Traceback (most recent call last):
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
>     resp = self._pool.handle_request(req)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
>     raise UnsupportedProtocol(
> httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
>     response = self._client.send(
>                ^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
>     response = self._send_handling_auth(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
>     response = self._send_handling_redirects(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
>     response = self._send_single_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
>     response = transport.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
>     with map_httpcore_exceptions():
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
>     resp = self._pool.handle_request(req)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
>     raise UnsupportedProtocol(
> httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
>     response = self._client.send(
>                ^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
>     response = self._send_handling_auth(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
>     response = self._send_handling_redirects(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
>     response = self._send_single_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
>     response = transport.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
>     with map_httpcore_exceptions():
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
>     resp = self._pool.handle_request(req)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
>     raise UnsupportedProtocol(
> httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 926, in _request
>     response = self._client.send(
>                ^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
>     response = self._send_handling_auth(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
>     response = self._send_handling_redirects(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
>     response = self._send_single_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
>     response = transport.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
>     with map_httpcore_exceptions():
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/satyamtiwary/Documents/Pytorch-Things/personal-graph/personal_graph/text.py", line 11, in text_to_graph
>     kg = graph_generator.generate(text)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Documents/Pytorch-Things/personal-graph/personal_graph/graph_generator/generator.py", line 37, in generate
>     knowledge_graph = client.chat.completions.create(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/client.py", line 74, in create
>     return self.create_fn(
>            ^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/patch.py", line 147, in new_create_sync
>     response = retry_sync(
>                ^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/retry.py", line 143, in retry_sync
>     for attempt in max_retries:
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 347, in __iter__
>     do = self.iter(retry_state=retry_state)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
>     raise retry_exc.reraise()
>           ^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
>     raise self.last_attempt.result()
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
>     return self.__get_result()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
>     raise self._exception
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/instructor/retry.py", line 146, in retry_sync
>     response = func(*args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 667, in create
>     return self._post(
>            ^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1208, in post
>     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 897, in request
>     return self._request(
>            ^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 950, in _request
>     return self._retry_request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1021, in _retry_request
>     return self._request(
>            ^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 950, in _request
>     return self._retry_request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1021, in _retry_request
>     return self._request(
>            ^^^^^^^^^^^^^^
>   File "/Users/satyamtiwary/Library/Caches/pypoetry/virtualenvs/personal-graph-TCeuOf-h-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 960, in _request
>     raise APIConnectionError(request=request) from err
> openai.APIConnectionError: Connection error.
> ```

We need to pass LiteLLM base url and token to generate text using GraphGenerator class.

**Comment by anubhuti24** [comment]
Since we are using default model name i.e openai/gpt-3.5-turbo we need to pass in the LiteLLM url and token.
Else we can just pass the model name directly and it's api key, if do not want to use LiteLLM
